package agenda;


/**
* agenda/AgendaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Terça-feira, 14 de Outubro de 2014 09h18min34s BRT
*/

abstract public class AgendaHelper
{
  private static String  _id = "IDL:agenda/Agenda:1.0";

  public static void insert (org.omg.CORBA.Any a, agenda.Agenda that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static agenda.Agenda extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (agenda.AgendaHelper.id (), "Agenda");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static agenda.Agenda read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AgendaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, agenda.Agenda value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static agenda.Agenda narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof agenda.Agenda)
      return (agenda.Agenda)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      agenda._AgendaStub stub = new agenda._AgendaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static agenda.Agenda unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof agenda.Agenda)
      return (agenda.Agenda)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      agenda._AgendaStub stub = new agenda._AgendaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
