package agenda;


/**
* agenda/ContactAlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Terça-feira, 14 de Outubro de 2014 09h18min34s BRT
*/

public final class ContactAlreadyExists extends org.omg.CORBA.UserException
{
  public String name = null;

  public ContactAlreadyExists ()
  {
    super(ContactAlreadyExistsHelper.id());
  } // ctor

  public ContactAlreadyExists (String _name)
  {
    super(ContactAlreadyExistsHelper.id());
    name = _name;
  } // ctor


  public ContactAlreadyExists (String $reason, String _name)
  {
    super(ContactAlreadyExistsHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class ContactAlreadyExists
