package agenda;


/**
* agenda/Contact.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Terça-feira, 14 de Outubro de 2014 09h18min34s BRT
*/

public final class Contact implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String phoneNumber = null;

  public Contact ()
  {
  } // ctor

  public Contact (String _name, String _phoneNumber)
  {
    name = _name;
    phoneNumber = _phoneNumber;
  } // ctor

} // class Contact
