package agenda;

/**
* agenda/ContactHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Terça-feira, 14 de Outubro de 2014 09h18min34s BRT
*/

public final class ContactHolder implements org.omg.CORBA.portable.Streamable
{
  public agenda.Contact value = null;

  public ContactHolder ()
  {
  }

  public ContactHolder (agenda.Contact initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = agenda.ContactHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    agenda.ContactHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return agenda.ContactHelper.type ();
  }

}
