package agenda;

/**
* agenda/ContactAlreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Terça-feira, 14 de Outubro de 2014 09h18min34s BRT
*/

public final class ContactAlreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public agenda.ContactAlreadyExists value = null;

  public ContactAlreadyExistsHolder ()
  {
  }

  public ContactAlreadyExistsHolder (agenda.ContactAlreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = agenda.ContactAlreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    agenda.ContactAlreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return agenda.ContactAlreadyExistsHelper.type ();
  }

}
